-- begin RESTAURANT_ORDER
alter table RESTAURANT_ORDER add constraint FK_RESTAURANT_ORDER_ON_SHOP_NAME foreign key (SHOP_NAME_ID) references RESTAURANT_SHOP(ID)^
create index IDX_RESTAURANT_ORDER_ON_SHOP_NAME on RESTAURANT_ORDER (SHOP_NAME_ID)^
-- end RESTAURANT_ORDER
-- begin RESTAURANT_SHOP
create unique index IDX_RESTAURANT_SHOP_UNIQ_NAME on RESTAURANT_SHOP (NAME) ^
-- end RESTAURANT_SHOP
-- begin RESTAURANT_USER
create unique index IDX_RESTAURANT_USER_UNIQ_NAME on RESTAURANT_USER (NAME) ^
-- end RESTAURANT_USER

-- begin RESTAURANT_ORDER_MENU_LINK
alter table RESTAURANT_ORDER_MENU_LINK add constraint FK_ORDMEN_ON_ORDER foreign key (ORDER_ID) references RESTAURANT_ORDER(ID)^
alter table RESTAURANT_ORDER_MENU_LINK add constraint FK_ORDMEN_ON_MENU foreign key (MENU_ID) references RESTAURANT_MENU(ID)^
-- end RESTAURANT_ORDER_MENU_LINK

-- begin RESTAURANT_USER_ORDER
alter table RESTAURANT_USER_ORDER add constraint FK_RESTAURANT_USER_ORDER_ON_USER_ID foreign key (USER_ID_ID) references SEC_USER(ID)^
create index IDX_RESTAURANT_USER_ORDER_ON_USER_ID on RESTAURANT_USER_ORDER (USER_ID_ID)^
-- end RESTAURANT_USER_ORDER
-- begin RESTAURANT_MENU
alter table RESTAURANT_MENU add constraint FK_RESTAURANT_MENU_ON_NAME foreign key (NAME_ID) references RESTAURANT_SHOP(ID)^
create index IDX_RESTAURANT_MENU_ON_NAME on RESTAURANT_MENU (NAME_ID)^
-- end RESTAURANT_MENU
