-- begin RESTAURANT_ORDER
alter table RESTAURANT_ORDER add constraint FK_RESTAURANT_ORDER_ON_USER_ORDER foreign key (USER_ORDER) references SEC_USER(ID)^
alter table RESTAURANT_ORDER add constraint FK_RESTAURANT_ORDER_ON_SHOP_NAME foreign key (SHOP_NAME_ID) references RESTAURANT_SHOP(ID)^
create index IDX_RESTAURANT_ORDER_ON_USER_ORDER on RESTAURANT_ORDER (USER_ORDER)^
create index IDX_RESTAURANT_ORDER_ON_SHOP_NAME on RESTAURANT_ORDER (SHOP_NAME_ID)^
-- end RESTAURANT_ORDER
-- begin RESTAURANT_SHOP
alter table RESTAURANT_SHOP add constraint FK_RESTAURANT_SHOP_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_RESTAURANT_SHOP_UNIQ_NAME on RESTAURANT_SHOP (NAME) ^
create index IDX_RESTAURANT_SHOP_ON_USER on RESTAURANT_SHOP (USER_ID)^
-- end RESTAURANT_SHOP
-- begin RESTAURANT_MENU
alter table RESTAURANT_MENU add constraint FK_RESTAURANT_MENU_ON_SHOP foreign key (SHOP_ID) references RESTAURANT_SHOP(ID)^
create index IDX_RESTAURANT_MENU_ON_SHOP on RESTAURANT_MENU (SHOP_ID)^
-- end RESTAURANT_MENU
-- begin RESTAURANT_ORDER_MENU_LINK
alter table RESTAURANT_ORDER_MENU_LINK add constraint FK_ORDMEN_ON_ORDER foreign key (ORDER_ID) references RESTAURANT_ORDER(ID)^
alter table RESTAURANT_ORDER_MENU_LINK add constraint FK_ORDMEN_ON_MENU foreign key (MENU_ID) references RESTAURANT_MENU(ID)^
-- end RESTAURANT_ORDER_MENU_LINK
