alter table RESTAURANT_ORDER add constraint FK_RESTAURANT_ORDER_ON_SHOP_NAME foreign key (SHOP_NAME_ID) references RESTAURANT_SHOP(ID);
create index IDX_RESTAURANT_ORDER_ON_SHOP_NAME on RESTAURANT_ORDER (SHOP_NAME_ID);
