alter table RESTAURANT_ORDER add constraint FK_RESTAURANT_ORDER_ON_USER_ORDER foreign key (USER_ORDER) references SEC_USER(ID);
create index IDX_RESTAURANT_ORDER_ON_USER_ORDER on RESTAURANT_ORDER (USER_ORDER);
