alter table RESTAURANT_USER_ORDER add constraint FK_RESTAURANT_USER_ORDER_ON_USER_ID foreign key (USER_ID_ID) references SEC_USER(ID);
create index IDX_RESTAURANT_USER_ORDER_ON_USER_ID on RESTAURANT_USER_ORDER (USER_ID_ID);
