alter table RESTAURANT_ORDER add constraint FK_RESTAURANT_ORDER_ON_USER_ORDER foreign key (USER_ORDER_ID) references RESTAURANT_USER_ORDER(ID);
create index IDX_RESTAURANT_ORDER_ON_USER_ORDER on RESTAURANT_ORDER (USER_ORDER_ID);
